import AdvancedMultiplicationWorld.Level1
import AdvancedMultiplicationWorld.Level2
import AdvancedMultiplicationWorld.Level3
-- import AdvancedMultiplicationWorld.Level4 -- bugbug
/-!
# Advanced Multiplication World

Welcome to Advanced Multiplication World! Before attempting this
world you should have completed seven other worlds, including
[Multiplication World](../MultiplicationWorld.lean.md) and
[Advanced Addition World](../AdvancedAdditionWorld.lean.md).
There are four levels in this world.

Let's dive in [Level 1](./AdvancedMultiplicationWorld/Level1.lean.md)
-/