lake build MyNat
lake build TutorialWorld
lake build AdditionWorld
lake build MultiplicationWorld
lake build PowerWorld
lake build FunctionWorld
lake build PropositionWorld
lake build AdvancedPropositionWorld
lake build AdvancedAdditionWorld
